#!/bin/bash

HOME=/home/disco4/afalcione/OPER

YEAR_ANALYSIS=$1
MONTH_ANALYSIS=$2
DAY_ANALYSIS=$3
HOUR_ANALYSIS=$4
MINUTE_ANALYSIS=$5

YEAR_MIN=$6
MONTH_MIN=$7
DAY_MIN=$8
HOUR_MIN=$9
MINUTE_MIN=${10}

YEAR_MAX=${11}
MONTH_MAX=${12}
DAY_MAX=${13}
HOUR_MAX=${14}
MINUTE_MAX=${15}

cat << End_Of_Namelist9 | sed -e 's/#.*//; s/  *$//' > ./namelist.input
&wrfvar1
write_increments=true,
print_detail_radar=true,
print_detail_grad=false,
print_detail_be=false,
print_detail_outerloop=false,
/
&wrfvar2
calc_w_increment=true,
/
&wrfvar3
/
&wrfvar4                    
use_synopobs=true,
use_shipsobs=true,
use_metarobs=false,
use_soundobs=true,
use_mtgirsobs=false,
use_pilotobs=false,
use_airepobs=false,
use_geoamvobs=false,
use_polaramvobs=false,
use_bogusobs=false,
use_buoyobs=false,
use_profilerobs=false,
use_satemobs=false,
use_gpspwobs=false,
use_gpsrefobs=false,
use_qscatobs=false,
use_radarobs=false,
use_radar_rv=false,
use_radar_rf=false,
use_airsretobs=false,
/
&wrfvar5
/
&wrfvar6
max_ext_its=1,
ntmax=75,
eps=0.001,
/
&wrfvar7
cv_options=3,
/
&wrfvar8
/
&wrfvar9
/
&wrfvar10
/
&wrfvar11
/
&wrfvar12
/
&wrfvar13
/
&wrfvar14
/
&wrfvar15
/
&wrfvar16
/
&wrfvar17
analysis_type="QC-OBS",
/
&wrfvar18
analysis_date=${YEAR_ANALYSIS}-${MONTH_ANALYSIS}-${DAY_ANALYSIS}_${HOUR_ANALYSIS}:${MINUTE_ANALYSIS}:00.0000,
/
&wrfvar19
/
&wrfvar20
/
&wrfvar21
time_window_min=${YEAR_MIN}-${MONTH_MIN}-${DAY_MIN}_${HOUR_MIN}:${MINUTE_MIN}:00.0000,
/
&wrfvar22
time_window_max=${YEAR_MAX}-${MONTH_MAX}-${DAY_MAX}_${HOUR_MAX}:${MINUTE_MAX}:00.0000,
/
&wrfvar23
/
&time_control
start_year=${YEAR_ANALYSIS},
start_month=${MONTH_ANALYSIS},
start_day=${DAY_ANALYSIS},
start_hour=${HOUR_ANALYSIS},
end_year=${YEAR_END},
end_month=${MONTH_END},
end_day=${DAY_END},
end_hour=${HOUR_END},
/
&fdda
grid_fdda=1,
gfdda_inname="wrffdda_d<domain>",
gfdda_interval_m=360,
gfdda_end_h=6,
io_form_gfdda=2,
fgdt=0,
if_no_pbl_nudging_uv=0,
if_no_pbl_nudging_t=0,
if_no_pbl_nudging_q=0,
if_zfac_uv=0,
k_zfac_uv=10,
if_zfac_t=0,
k_zfac_t=10,
if_zfac_q=0,
k_zfac_q=10,
guv=0.0003,
gt=0.0003,
gq=0.0003,
if_ramping=0,
dtramp_min=60.0,
/
&domains
e_we=379,
e_sn=431,
e_vert=40,
dx=3000,
dy=3000,
/
&dfi_control
/
&tc
/
&physics
mp_physics=6,
ra_lw_physics=1,
ra_sw_physics=1,
radt=1,
sf_sfclay_physics=2,
sf_surface_physics=2,
bl_pbl_physics=2,
cu_physics=0,
cudt=0,
num_soil_layers=4,
mp_zero_out=2,
num_land_cat=21,
/
&scm
/
&dynamics
/
&bdy_control
/
&grib2
/
&fire
/
&namelist_quilt
/
&perturbation
/
End_Of_Namelist9
